# Configuration for Rosmaster Terminal Teleoperator
type: rosmaster_terminal

# Joint limits in degrees (min, max)
joint_limits:
  servo_1: [0, 180]
  servo_2: [0, 180] 
  servo_3: [0, 180]
  servo_4: [0, 180]
  servo_5: [0, 180]
  servo_6: [0, 180]

# Default starting positions (middle positions)
default_positions:
  servo_1: 90.0
  servo_2: 90.0
  servo_3: 90.0
  servo_4: 90.0
  servo_5: 90.0
  servo_6: 90.0
